version: "3.3"
services:
  db:
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - "mongodata:/data/db"
  web:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: unless-stopped
    volumes:
      - .:/app/node_app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - notused:/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Mexico_City
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - PORT=5000

volumes:
  mongodata:
  notused:
